language: python
python:
  - 3.6
  - 3.5
env:
  - TORTOISE_TEST_DB="sqlite:///tmp/test-{}.sqlite"
  - TORTOISE_TEST_DB="postgres://postgres:@127.0.0.1:5432/test_{}"
dist: trusty
sudo: false
addons:
  postgresql: "9.4"
services:
  - postgresql
cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - make ci
after_success:
  - coveralls
